name: build-petr4

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout/main
        uses: actions/checkout@v1
      
      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v1
        with:
          ocaml-version: '4.14.0'

      - name: build-ubuntu
        run: ./.github/scripts/build-petr4-ubuntu.sh
        shell: bash

      - name: Run Tests
        run: ./.github/scripts/test-gcl-compiler.sh
        shell: bash

  build-macos-latest:
    runs-on: macos-latest

    steps: 
      - name: checkout-main
        uses: actions/checkout@v1
        
      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v1
        with: 
          ocaml-version: '4.14.0'
        
      - name: build-macos
        run: ./.github/scripts/build-petr4-macos.sh
        shell: bash

      - name: Run Tests
        run: ./.github/scripts/test-gcl-compiler.sh
        shell: bash
