name: ci-typechecker

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["push-petr4-docker-img"]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  petr4-vs-p4c:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
      image: pataei/petr4:main
    steps: 
      - name: update git version
        run: |
          sudo apt-get install -y software-properties-common 
          sudo apt-get update 
          sudo add-apt-repository -y ppa:git-core/ppa 
          sudo apt-get update 
          sudo apt-get install -y git
      - uses: actions/checkout@v2
      - name: typecheck test petr4 vs p4c
        run: ./.github/scripts/typecheck-petr4-vs-p4c.sh
        shell: bash
      - name: add result of type checking to git repo
        run: |
          git config --global user.email "paris.ataei@gmail.com"
          git config --global user.name  "Github Action Bot GO!"
          git config --global --add safe.directory /__w/petr4/petr4
          git add ci-test/type-checking/*
          git commit -am "write type to output files"
          git push origin
